### ISSUE TITLE
game crashes while talking in rundown map

### ISSUE THREAD

**Issue by FinbarSchenk** [WWYDF/OpenPA#3]
Hello my Friend and i have the problem that his game crashes when he talks. he can talk when he is in the lobby and in the drop but when he tries to talk while being in the map, his game crashes then.

**Comment by WWYDF** [comment]
Are you using v2.1 (Thunderstore) or v3.0 (latest dev build)?

Sorry I hadn't seen this 😅

**Comment by FinbarSchenk** [comment]
It is fine we managed to get it running, your Dev-Version works for us,
still wanted to point it out for you
